### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by bamorgan13** [cfo8473/Disaccord#2]
### Users
 - [x] Add `joinedServerIds` array in order to know which `servers` a `user` is a member of (to display `server` icons on nav bar)
### Servers
 - [x] Add `joinedChannelIds` array in order to know which `channels` are in a `server` (to display only `channels` a `user` has privileges to in nav bar)
### Channels
 - [x] Add `messageIds` array in order to know which posts are in a channel
 - [x] Pins are simply messages that have been given a 'pinned' designation. I would structure this as a `pinIds` array that references the `messages` slice of state instead of storing the actual body of the message.
### Messages
 - [x] Add a messages/posts/etc. slice of the store under entities that will keep track of the posts in a channel. It should store the id, body, authorId, channelId, and timePosted. If a channel is displayed, it should be able to iterate over its messageIds and create a post component based on the details it grabs from this corresponding slice of the store.
### Additional Reducers
 - [x] Add a `session` slice top level to keep track of `currentUserId`, which we'll use in frontend auth. Check out the [bluebird example](https://github.com/appacademy/bluebird/wiki/sample-state).
 - [x] Add an `errors` slice top level to keep track of your various errors (session errors, form errors, etc.)

One key missing piece is the `messages`/`posts` that `users` create, which we'll want to keep in our store to easily pass as props in order to render them in our `channel` components.
Having the relationship ids in the store (which `servers` a `user` is a member of, `channels` the `user` has access to in a `server`, etc.) can be very helpful when trying to determine which content to render (iterating over the `user's` `joinedServerIds` to create a component for each of those `servers` in the nav bar, etc.), so I suggested some useful relationships that you will most likely need.
You may eventually be adding on to what you keep in your store as you run into more development challenges or advanced features that require specific data, but after a couple tweaks you'll have a good foundation to get the project started!

**Comment by cfo8473** [comment]
Thank you! I'm not quite sure if I did the pinIds array correctly so I'll go over it again after I finish some backend route fixes
