### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by bamorgan13** [cfo8473/Disaccord#3]
### Users
 - [x] Add an `:id` wildcard to the end of your `GET` route
### Channels
 - [x] I think nesting the channels under the servers is a great approach. When doing so, rails will automatically do it in the form of `GET /api/servers/:server_id/channels/`, specifying that these are channels that we are getting. The `:id` is generally reserved for the model that we are concerned with in this route. Since the controller is for channels, I would switch your `:id` and `:channelId` references to be `:server_id` and `:id` references respectively.
 (I know discord's frontend routes have the 'channels/:serverId/:channelId' format, but we can accomplish this with react on the frontend and still have a semantic structure on the backend)
 - [x] To return all channels in a server, you can do a `GET /api/servers/:server_id/channels`, leaving out the `:id`.
 - [x] Similarly, your `POST` route should specify you are adding a channel, `/api/servers/:server_id/channels`
 - [x] When you already have a `channel's` `id`, you no longer need a reference to the `server` it is associated with, so your `PATCH` and `DELETE` requests can go directly to `/api/channels/:id`
### Messages
 - [x] Following the same decoupling of the frontend from the backend, if we have a reference to the channel's id, we don't need to add the server's id as well. We can structure our routes as `GET /api/channels/:channel_id/messages` to get all of a channels messages, and so on.
 - [x] We can also key directly into the message for `PATCH` and `DELETE`, `/api/messages/:id`, instead of nesting them.

 Good job! A couple of changes to which routes are nested and getting rid of some unnecessary ids, but you have a good framework set up.

**Comment by cfo8473** [comment]
Good catch on the paths, thanks!
