### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by bamorgan13** [cfo8473/Disaccord#4]
### Channels
 - [x] How is `/servers/:id/:channelId` different from `/servers/:id/:channelId/messages`? I don't think the `messages` route is needed, since a `channel's` 'display' is essentially just its index of `messages`.
 - [x] A form component should be present to make a new message for this channel.
### Users
 - [x] The `UsersIndex` component should be visible from the `channel` page, so I don't think a new route is needed, the component should just be moved.
### ChannelForm
 - [x] If the form is for making a new channel, it shouldn't need a `:channelId`, it should just be present either on the `/servers/:id` route as a modal or on a `/servers/:id/newChannel` route specifically for the form.

 Good work! I think some of your components can be moved to the same routes and just displayed on different portions of the app. Let me know if any of this needs clarification!

**Comment by cfo8473** [comment]
Thanks! I'm not sure if I hit the right routes and components so I'm going to read the issues again and think about it a little bit. I'm still a little hazy on this stuff.

**Comment by bamorgan13** [comment]
No worries! One additional change from what you have made so far would be related to the server creation form. On discord it looks like the server creation form appears as a modal, not changing your route at all when you click on it. I would move your component to be nested under your `ServerIndex` and remove the `/servers/new` route.
